Repository fluxcd/helm-operator, pull requests merged in 2019-10, with the labels that each got.

#58 Update Flux dependency to `v1.15.0`
  cmd/helm-operator/main.go
  go.mod
  go.sum
  pkg/apis/helm.fluxcd.io/v1/types.go
  pkg/release/release.go
  pkg/tools.go
Labels: build

#61 Make release build cope with `v` prefixed tags
  .circleci/config.yml
  docker/image-tag
Labels: build

#66 De-experimental-ise `--workers` flag
  cmd/helm-operator/main.go
  docs/faq.md
  docs/references/operator.md
Labels: documentation, enhancement

#65 Fix git.ssh.secret parameter name in chart documentation
  chart/helm-operator/README.md
Labels: chart, documentation

#82 add documentation for timeout, resetValues and forceUpgrade.
  docs/references/helmrelease-custom-resource.md
Labels: docs
