Repository fluxcd/helm-operator, pull requests merged in 2019-08, with the labels that each got.

#20 Tidy documentation and templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/main.workflow
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: documentation

#21 Update Docker labels to new repository
  docker/Dockerfile.helm-operator
Labels: build

#22 Various documentation fixes
  README.md
  docs/faq.md
  docs/references/helmrelease-custom-resource.md
  docs/troubleshooting.md
  docs/tutorials/get-started.md
  internal_docs/releasing.md
Labels: documentation

#23 Add additional printer columns
  .circleci/config.yml
  chart/helm-operator/templates/crd.yaml
  deploy/flux-helm-release-crd.yaml
  pkg/install/generated_templates.gogen.go
  pkg/install/templates/flux-helm-release-crd.yaml.tmpl
Labels: chart, manifests

#24 Add descriptions for the CRD fields
  chart/helm-operator/templates/crd.yaml
  deploy/flux-helm-release-crd.yaml
  docs/references/helmrelease-custom-resource.md
Labels: documentation

#26 Use Helm chart in e2e tests
  test/e2e/run.sh
Labels: build

#28 CircleCI release config hotfixes
  .circleci/config.yml
Labels: build

#29 Release chart v0.1.0
  .circleci/config.yml
  chart/helm-operator/CHANGELOG.md
  chart/helm-operator/Chart.yaml
Labels: chart

#32 Add Kustomize install tutorial to docs and other fixes
  chart/helm-operator/README.md
  deploy/kustomization.yaml
  docs/tutorials/get-started-kustomize.md
  docs/tutorials/get-started.md
  docs/tutorials/index.rst
Labels: documentation

#35 Correct the documented default for createCRD
  chart/helm-operator/README.md
Labels: chart, documentation
