Repository fluxcd/helm-operator, pull requests merged in 2020-07, with the labels that each got.

#491 Fix: slightly increase GC offset anonymous files
  pkg/helm/v3/dependency.go
Labels: bug

#490 Fix: prevent spurious upgrades for semver ranges
  pkg/helm/helm.go
  pkg/helm/v2/chart.go
  pkg/helm/v3/chart.go
  pkg/release/release.go
Labels: bug

#478 Fix: longer timeout for annotator
  pkg/release/annotator.go
Labels: bug

#500 increase liveness and readiness probe failureThreshold during tests
  test/e2e/lib/install.bash
Labels: build

#507 Fix kubeconfig override in chart/deployment
  chart/helm-operator/templates/deployment.yaml
Labels: chart

#502 Fix Readme (configureRepositories.cacheVolumeName)
  chart/helm-operator/README.md
Labels: chart
